package entityClasses;

import java.sql.Timestamp;

/**
 * <p> Title: Post Class </p>
 * * <p> Description: This entity class represents a single post in the
 * discussion board. It holds all the necessary data for a post, such as its ID,
 * title, author, content, timestamp, and the thread it belongs to. This class
 * serves as the data model for posts within the application, mirroring the structure
 * of the 'posts' database table. </p>
 * * <p> Copyright: Lynn Robert Carter © 2025 </p> // Copied from baseline
 * * @author Amaan Sayed
 * * @version 2.10 HW2 Implementation with Threads and Documentation
 */
public class Post {

    /* Attributes ********************************************************************************/
    
    // Private attributes ensure data encapsulation, following standard object-oriented practice.
    private int postID;             // Unique identifier, typically generated by the database upon insertion.
    private String title;           // The subject line of the post, required for context.
    private String authorUsername;  // Username of the User who created the post. Links the post to a user record.
    private String content;         // The main body/text of the post. Stored as CLOB in DB for potentially long text.
    private Timestamp timestamp;    // The date and time when the post was created/saved. Automatically generated.
    
    // HW2 Revision: Added threadName attribute based on detailed user stories.
    // This allows posts to be categorized into different discussion topics.
    private String threadName;

    /* Constructors ******************************************************************************/
    
    /**
     * <p> Method: Post() - Default constructor. </p>
     * * <p> Description: Initializes a new, empty Post object. It sets the default thread name
     * [cite_start]to "General" as specified in the user stories[cite: 43]. This constructor is useful when
     * creating a Post object programmatically before all data is available (e.g., before saving to DB). </p>
     */
    public Post() {
        // HW2 Revision: Set the default thread name.
        // Why? User story requires a default if none is specified by the user. "General" is a sensible default.
        this.threadName = "General"; 
    }

    /**
     * <p> Method: Post(...) - Parameterized constructor. </p>
     * * <p> Description: Initializes a new Post object with all attributes provided. This is
     * typically used when reconstructing a Post object after retrieving its data from the database.
     * It includes logic to default the thread name to "General" if the provided
     * name is null or just whitespace, ensuring data consistency. </p>
     * * @param postID The unique identifier for the post.
     * @param title The title of the post.
     * @param authorUsername The username of the user who created the post.
     * @param content The main body content of the post.
     * @param timestamp The date and time the post was created.
     * @param threadName The name of the discussion thread this post belongs to.
     */
    public Post(int postID, String title, String authorUsername, String content, Timestamp timestamp, String threadName) {
        this.postID = postID;
        this.title = title;
        this.authorUsername = authorUsername;
        this.content = content;
        this.timestamp = timestamp;
        // HW2 Revision: Initialize threadName, default if null/empty.
        // Why this check? Ensures the Post object always has a valid, non-null thread name,
        // simplifying downstream logic and adhering to the user story default.
        this.threadName = (threadName == null || threadName.trim().isEmpty()) ? "General" : threadName.trim();
    }

    /* Accessors and Mutators (Getters and Setters) ********************************************/
    
    /**
     * <p> Method: getPostID() </p>
     * <p> Description: Gets the unique identifier for the post. </p>
     * @return The integer post ID.
     */
    public int getPostID() {
        return postID;
    }

    /**
     * <p> Method: setPostID() </p>
     * <p> Description: Sets the unique identifier for the post. This is usually only called
     * by the database layer when reconstructing an object from a query result. </p>
     * @param postID The integer post ID.
     */
    public void setPostID(int postID) {
        this.postID = postID;
    }

    /**
     * <p> Method: getTitle() </p>
     * <p> Description: Gets the title (subject line) of the post. </p>
     * @return The post title String.
     */
    public String getTitle() {
        return title;
    }

    /**
     * <p> Method: setTitle() </p>
     * <p> Description: Sets the title (subject line) of the post. </p>
     * @param title The post title String. Input validation for non-emptiness should happen before calling this, typically in the Controller.
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * <p> Method: getAuthorUsername() </p>
     * <p> Description: Gets the username of the user who authored the post. </p>
     * @return The author's username String.
     */
    public String getAuthorUsername() {
        return authorUsername;
    }

    /**
     * <p> Method: setAuthorUsername() </p>
     * <p> Description: Sets the username of the user who authored the post. </p>
     * @param authorUsername The author's username String.
     */
    public void setAuthorUsername(String authorUsername) {
        this.authorUsername = authorUsername;
    }

    /**
     * <p> Method: getContent() </p>
     * <p> Description: Gets the main content body of the post. </p>
     * @return The post content String.
     */
    public String getContent() {
        return content;
    }

    /**
     * <p> Method: setContent() </p>
     * <p> Description: Sets the main content body of the post. </p>
     * @param content The post content String. Input validation for non-emptiness should happen before calling this.
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * <p> Method: getTimestamp() </p>
     * <p> Description: Gets the creation timestamp of the post. </p>
     * @return The Timestamp object indicating when the post was saved.
     */
    public Timestamp getTimestamp() {
        return timestamp;
    }

    /**
     * <p> Method: setTimestamp() </p>
     * <p> Description: Sets the creation timestamp of the post. Usually only set when retrieving
     * from the database. </p>
     * @param timestamp The Timestamp object.
     */
    public void setTimestamp(Timestamp timestamp) {
        this.timestamp = timestamp;
    }
    
    // HW2 Revision: Getter and Setter for threadName with Javadoc.
    /**
     * <p> Method: getThreadName() </p>
     * <p> Description: Gets the name of the discussion thread this post belongs to. </p>
     * @return The thread name String (e.g., "General", "Homework 1").
     */
    public String getThreadName() {
        return threadName;
    }

    /**
     * <p> Method: setThreadName() </p>
     * <p> Description: Sets the name of the discussion thread this post belongs to. Defaults to "General"
     * [cite_start]if the provided name is null or consists only of whitespace, aligning with user story[cite: 43]. </p>
     * @param threadName The thread name String.
     */
    public void setThreadName(String threadName) {
        // Why this check? [cite_start]Ensures consistency and avoids null/empty values per user story[cite: 43].
        // Using trim() handles potential whitespace issues.
        this.threadName = (threadName == null || threadName.trim().isEmpty()) ? "General" : threadName.trim();
    }
}