package entityClasses;

import java.sql.Timestamp;

/**
 * <p> Title: Reply Class </p>
 * * <p> Description: This entity class represents a single reply to a post on the
 * discussion board. It includes a postID to link it back to its parent post,
 * mirroring the structure of the 'replies' database table. </p>
 * * <p> Copyright: Lynn Robert Carter © 2025 </p> // Copied from baseline
 * * @author Amaan Sayed
 * * @version 2.10 HW2 Implementation with Documentation
 */
public class Reply {

    /* Attributes ********************************************************************************/
    
    // Private attributes for encapsulation.
    private int replyID;            // Unique identifier generated by the database.
    private int postID;             // Foreign key linking this reply to the parent Post in the 'posts' table.
    private String authorUsername;  // Username of the User who created the reply.
    private String content;         // The main body/text of the reply.
    private Timestamp timestamp;    // The date and time when the reply was created/saved.

    /* Constructors ******************************************************************************/
    
    /**
     * <p> Method: Reply() - Default constructor. </p>
     * * <p> Description: Initializes a new, empty Reply object. Useful when creating a reply
     * object programmatically before saving it to the database. </p>
     */
    public Reply() {
        // No default values needed beyond standard Java defaults (0 for int, null for objects).
    }

    /**
     * <p> Method: Reply(...) - Parameterized constructor. </p>
     * * <p> Description: Initializes a new Reply object with all attributes provided. This is
     * typically used when reconstructing a Reply object after retrieving its data from the
     * database. </p>
     * * @param replyID The unique identifier for the reply.
     * @param postID The ID of the post this reply belongs to.
     * @param authorUsername The username of the author of the reply.
     * @param content The main body content of the reply.
     * @param timestamp The date and time the reply was created.
     */
    public Reply(int replyID, int postID, String authorUsername, String content, Timestamp timestamp) {
        this.replyID = replyID;
        this.postID = postID;
        this.authorUsername = authorUsername;
        this.content = content;
        this.timestamp = timestamp;
    }

    /* Accessors and Mutators (Getters and Setters) ********************************************/
    
    /**
     * <p> Method: getReplyID() </p>
     * <p> Description: Gets the unique identifier for the reply. </p>
     * @return The integer reply ID.
     */
    public int getReplyID() {
        return replyID;
    }

    /**
     * <p> Method: setReplyID() </p>
     * <p> Description: Sets the unique identifier for the reply. Usually only set when
     * retrieving from the database. </p>
     * @param replyID The integer reply ID.
     */
    public void setReplyID(int replyID) {
        this.replyID = replyID;
    }

    /**
     * <p> Method: getPostID() </p>
     * <p> Description: Gets the ID of the parent post this reply is associated with. </p>
     * @return The integer post ID of the parent post.
     */
    public int getPostID() {
        return postID;
    }

    /**
     * <p> Method: setPostID() </p>
     * <p> Description: Sets the ID of the parent post this reply is associated with. </p>
     * @param postID The integer post ID of the parent post.
     */
    public void setPostID(int postID) {
        this.postID = postID;
    }

    /**
     * <p> Method: getAuthorUsername() </p>
     * <p> Description: Gets the username of the user who authored the reply. </p>
     * @return The author's username String.
     */
    public String getAuthorUsername() {
        return authorUsername;
    }

    /**
     * <p> Method: setAuthorUsername() </p>
     * <p> Description: Sets the username of the user who authored the reply. </p>
     * @param authorUsername The author's username String.
     */
    public void setAuthorUsername(String authorUsername) {
        this.authorUsername = authorUsername;
    }

    /**
     * <p> Method: getContent() </p>
     * <p> Description: Gets the main content body of the reply. </p>
     * @return The reply content String.
     */
    public String getContent() {
        return content;
    }

    /**
     * <p> Method: setContent() </p>
     * <p> Description: Sets the main content body of the reply. Input validation for
     * non-emptiness should happen before calling this. </p>
     * @param content The reply content String.
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * <p> Method: getTimestamp() </p>
     * <p> Description: Gets the creation timestamp of the reply. </p>
     * @return The Timestamp object indicating when the reply was saved.
     */
    public Timestamp getTimestamp() {
        return timestamp;
    }

    /**
     * <p> Method: setTimestamp() </p>
     * <p> Description: Sets the creation timestamp of the reply. Usually only set when retrieving
     * from the database. </p>
     * @param timestamp The Timestamp object.
     */
    public void setTimestamp(Timestamp timestamp) {
        this.timestamp = timestamp;
    }
}